### ISSUE TITLE
Cmake configuration needs mgpuutil.cpp

### ISSUE THREAD

**Issue by webanck** [cudpp/cudpp#153]
Hello, I am trying to install cudpp on ubuntu and during the cmake configuration, I am not able to generate the makefiles because the mgpuutil.cpp is missing.
Looking for this file at [ext/moderngpu/src/](ext/moderngpu/src/) I found an empty directory that I filled with the files from [NVlabs/moderngpu](https://github.com/NVlabs/moderngpu).
I wonder if this is the expected installation process?

**Comment by Laurawly** [comment]
Hello, cub and moderngpu libraries are added as submodules under folder ext/ in cudpp 2.2, you need the following two lines to pull those in under the cudpp/ root directory.
$ git init
$ git update

**Comment by webanck** [comment]
Thanks for the answer but I downloaded cudpp in the zip file so you are telling me to get it through git pull instead?

**Comment by Laurawly** [comment]
Yes, I'm afraid so. I think it's a more convenient way to install those dependent libraries.

**Comment by webanck** [comment]
Ok, I just made a git clone of the repository but git update isn't valid and git pull does nothing because the files are up to date after a fresh clone.
So am I missing something?

**Comment by Laurawly** [comment]
After you git clone the repo, you need the following two lines to get the submodules
$ git submodule init
$ git submodule update

**Comment by Laurawly** [comment]
And the submodules should be fetched under cudpp/ repo, I think there's a typo in my first comment.

**Comment by webanck** [comment]
Yeah exactly, it worked with submodule, thx!

**Comment by Laurawly** [comment]
No problem.

**Comment by harrism** [comment]
Perhaps we should get rid of the .zip files and provide detailed installation instructions in the wiki.

**Comment by Laurawly** [comment]
Yes, Mark. I've written the installation method under "Building cudpp" on
cudpp 2.2 main website. And I've checked it in under master branch. After
reviewed by John, I can release it to the website and delete the zip file.

**Comment by wisllayvitrio** [comment]
@Laurawly I'm afraid your changes in the Building CUDPP section weren't commited. I reached this issue following the same steps as the OP.

**Comment by Laurawly** [comment]
@wisllayvitrio Yes, you're right. I've just committed the changes, you can check it out now. http://cudpp.github.io/cudpp/2.2/building-cudpp.html

**Comment by kellyrowland** [comment]
Hello,

The zip files still have not been deleted; I downloaded that and had to find this issue in order to solve the same problem discussed above.

Thanks!

**Comment by Laurawly** [comment]
Hello Kelly,

It seems that we are unable to disable the "Download ZIP" github option
according to this post http://cudpp.github.io/cudpp/2.2/building-cudpp.html.
But you can follow the instructions on the CUDPP building page
http://cudpp.github.io/cudpp/2.2/building-cudpp.html to install it.

Best,
Leyuan

**Comment by cwright7101** [comment]
I followed the instructions at (http://cudpp.github.io/cudpp/2.2/building-cudpp.html) as mentioned above,

$ git clone https://github.com/cudpp/cudpp.git
$ git submodule init
$ git submodule update

and I get the error:
fatal: reference is not a tree: 9c335b9aacff874253c2f3e79c643230317438f0
Unable to checkout '9c335b9aacff874253c2f3e79c643230317438f0' in submodule path 'ext/cub'

I downloaded cub-1.7.4 and put into CFLAGS and cudpp will compile some of the way, but it dies with the following message:

1 error detected in the compilation of "/tmp/tmpxft_00007a9d_00000000-6_multisplit_app.cpp1.ii".
CMake Error at cudpp_generated_multisplit_app.cu.o.cmake:266 (message):
  Error generating file
  /home/chris/Development/cudpp/build/src/cudpp/CMakeFiles/cudpp.dir/app/./cudpp_generated_multisplit_app.cu.o


I am using cuda-9.0 (V9.0.176), gcc 5.4.0


Any help on this would be great!

**Comment by johans121** [comment]
I am getting the same errors as cwright7101....

**Comment by ghost** [comment]
New to CUDPP, I am failing with the same "Server does not allow request for unadvertised object" error.  Is there no solution?

**Comment by Jeoker** [comment]
have the same issue here. It seems to be a pretty new bug

**Comment by mas6700** [comment]
I fixed the problem with empty ext/moderngpu/src/  directory with the solution as described above with:
> git submodule init

Submodule 'ext/cub' (git://github.com/NVlabs/cub.git) registered for path 'ext/cub'
Submodule 'ext/moderngpu' (git://github.com/NVlabs/moderngpu.git) registered for path 'ext/moderngpu'

> git submodule update
Cloning into 'ext/cub'...
remote: Counting objects: 32642, done.
remote: Total 32642 (delta 0), reused 0 (delta 0), pack-reused 32642
Receiving objects: 100% (32642/32642), 16.49 MiB | 6.10 MiB/s, done.
Resolving deltas: 100% (28621/28621), done.
fatal: reference is not a tree: 9c335b9aacff874253c2f3e79c643230317438f0
Cloning into 'ext/moderngpu'...
remote: Counting objects: 1287, done.
remote: Total 1287 (delta 0), reused 0 (delta 0), pack-reused 1287
Receiving objects: 100% (1287/1287), 6.72 MiB | 5.13 MiB/s, done.
Resolving deltas: 100% (643/643), done.
Submodule path 'ext/moderngpu': checked out 'b6b3ed52f8f7478b969e05242980c97ff21a6ab0'
Unable to checkout '9c335b9aacff874253c2f3e79c643230317438f0' in submodule path 'ext/cub'

So I was able to configure and build the make file, but I now get the fatal compilation error due to the checkout error above:

../cudpp/src/cudpp/app/sa_app.cu:22:23: fatal error: cub/cub.cuh: No such file or directory
 #include "cub/cub.cuh"
                       ^
compilation terminated.
CMake Error at cudpp_generated_sa_app.cu.o.cmake:206 (message):
  Error generating
../cudpp/bin/linux64/src/cudpp/CMakeFiles/cudpp.dir/app/./cudpp_generated_sa_app.cu.o

I would really like to use cudapp so someone has or knows of a fix I would really appreciate it.

**Comment by Jeoker** [comment]
Guys, if you are still stuck with the submodule of this repo, maybe you would like to revert this repo to version 2.1 where no submodule was used at that time. However, you need to do some changes in the makefiles of that version in that the GPU architechture used at that time was too old

**Comment by mas6700** [comment]
I was able to get the cub directory directly from cudpp/ext/cub tree and download it and then install it manually in the cudpp/app directory. That worked but then I ran into the next problem where compiling the cudpp_hash directory (which is what I want to use) would not compile because I'm running CUDA 9.1 and the makefile is hard coded to use compute_20 which is not supported by CUDA 9.1. I set the compute mode to compute_50 in the CMAKE configuration but the cudpp_hash makefiles still retain the compute_20 (and sm_20). So as a last resort I just manually edited the cmake files and changed compute_20 to compute_50 (and sm_20 to sm_50), and the compilation finished! So I now have the cuda_hash libraries. Yippie! Now I just have to make this work with my code.

**Comment by fraserw** [comment]
I have run into the same issues as first reported by cwright. Submodules failing to update.

Using ubuntu 18.04 and cuda_10 with a 2080 RTX. Cuda installed in /usr/local/cuda

Any solution would be lovely!

fraserw@wtfrocket$  git clone https://github.com/cudpp/cudpp.git
```
Cloning into 'cudpp'...
remote: Enumerating objects: 9093, done.
remote: Total 9093 (delta 0), reused 0 (delta 0), pack-reused 9093
Receiving objects: 100% (9093/9093), 111.50 MiB | 7.72 MiB/s, done.
Resolving deltas: 100% (7184/7184), done.

```

fraserw@wtfrocket$ cd cudpp/
fraserw@wtfrocket$ git submodule init
```
Submodule 'ext/cub' (git://github.com/NVlabs/cub.git) registered for path 'ext/cub'
Submodule 'ext/moderngpu' (git://github.com/NVlabs/moderngpu.git) registered for path 'ext/moderngpu'

```

fraserw@wtfrocket$ git submodule update
```
Cloning into '/home/fraserw/git/cudpp/ext/cub'...
Cloning into '/home/fraserw/git/cudpp/ext/moderngpu'...
error: Server does not allow request for unadvertised object 9c335b9aacff874253c2f3e79c643230317438f0
Fetched in submodule path 'ext/cub', but it did not contain 9c335b9aacff874253c2f3e79c643230317438f0. Direct fetching of that commit failed.

```
