### ISSUE TITLE
CUDPP_APP_DATA_DIR not set by default

### ISSUE THREAD

**Issue by jowens** [cudpp/cudpp#164]
```
[ 71%] Building CXX object apps/cudpp_testrig/CMakeFiles/cudpp_testrig.dir/test_rand.cpp.o
/Users/jowens/Documents/working/cudpp/apps/cudpp_testrig/test_rand.cpp:111:63: error:
      use of undeclared identifier 'CUDPP_APP_DATA_DIR'
```

This only appears when setting `CUDPP_BUILD_APPLICATIONS` to `ON`:

```
$ cmake ../cudpp -DCUDPP_BUILD_APPLICATIONS:BOOL=ON
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
```

**Comment by jwmak** [comment]
The CUDPP_APP_DATA_DIR variable, which normally points to cudpp/apps/data/*, is not set in CMakeLists.txt because we do not want to include cudpp/apps/data/* in the master branch. When cloning the repo, the data in this directory would take too long to download. In the 'test' branch, we do include this directory, and we do set the CUDPP_APP_DATA_DIR variable. However, since some of the testing apps don't require any file data and don't use that directory, I will set the CUDPP_APP_DATA_DIR variable in CMakeLists.txt in the master branch. This way, the library can still be built, even without the data, when CUDPP_BUILD_APPLICATIONS is set to ON, and a subset of the testing apps can be run.

**Comment by jowens** [comment]
@jwmak, please make sure this is clear in the documentation and the release notes. Another alternative is including the data dir as a separate repo in the cudpp organization rather than a branch in cudpp (it seems non-ideal to have to track cudpp master branch in cudpp test branch and constantly update test branch with master branch as we update master branch).

**Comment by rav66** [comment]
Using submodules to include the test and data may be a good option
