### ISSUE TITLE
needs multisplit regression

### ISSUE THREAD

**Issue by jowens** [cudpp/cudpp#168]
In good news, `-all` regression appears to completely pass on OS X (woo!).

However, I don't see a multisplit regression at all, nothing multisplit-related in cudpp_testrig.cpp or when I run it with `-all`.

**Comment by jwmak** [comment]
There is test code for multisplit in test_multisplit.cpp, which is called in cudpp_testrig in branch 2.3. To test multisplit by itself, use cudpp_testrig -multisplit. There was an issue in the suffix-array tests that was affecting the multisplit tests, but this has been fixed in the latest changes, and the multisplit tests should now pass with -all.
